#!/usr/bin/env bash
# scripts/docker-init.sh
#
# One-shot init script cho Docker stack:
#  - Nếu .env chưa có  → sinh ngẫu nhiên DB_PASSWORD, DB_ROOT_PASSWORD, JWT_SECRET
#                        từ openssl, ghi ra .env (KHÔNG hỏi gì, KHÔNG in secret).
#  - Nếu .env đã có    → giữ nguyên (idempotent), không ghi đè.
#  - Sau đó (mặc định) chạy `docker compose up -d --build` luôn.
#
# Usage:
#   ./scripts/docker-init.sh           # init + up
#   ./scripts/docker-init.sh --no-up   # chỉ sinh .env, không up
#   ./scripts/docker-init.sh --force   # ghi đè .env hiện có (NGUY HIỂM)
#
# Tương thích: Linux, macOS, Windows Git Bash (openssl bundled).

set -euo pipefail

# Vào thư mục project root (parent của scripts/)
cd "$(dirname "$0")/.."

ENV_FILE=".env"
DO_UP=1
FORCE=0

for arg in "$@"; do
  case "$arg" in
    --no-up) DO_UP=0 ;;
    --force) FORCE=1 ;;
    -h|--help)
      sed -n '2,18p' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *) echo "Unknown arg: $arg" >&2; exit 2 ;;
  esac
done

# ── 1. Pre-flight checks ────────────────────────────────────
if ! command -v docker >/dev/null 2>&1; then
  echo "✗ Không tìm thấy 'docker'. Cài đặt Docker trước: https://docs.docker.com/get-docker/" >&2
  exit 1
fi
if ! docker compose version >/dev/null 2>&1; then
  echo "✗ Docker Compose plugin thiếu. Cần Docker Engine ≥ 24 với compose plugin." >&2
  exit 1
fi
if ! command -v openssl >/dev/null 2>&1; then
  echo "✗ Không tìm thấy 'openssl' — cần để sinh secret. Cài openssl rồi chạy lại." >&2
  exit 1
fi

# ── 2. Sinh .env nếu chưa có ────────────────────────────────
if [ -f "$ENV_FILE" ] && [ "$FORCE" -eq 0 ]; then
  echo "✓ .env đã tồn tại — giữ nguyên (dùng --force để ghi đè)"
else
  if [ -f "$ENV_FILE" ]; then
    BACKUP=".env.backup-$(date +%Y%m%d-%H%M%S)"
    cp "$ENV_FILE" "$BACKUP"
    echo "⚠ Backup .env hiện tại → $BACKUP"
  fi

  # 24 byte hex = 48 ký tự, KHÔNG có @ : / ? # & — an toàn cho DATABASE_URL
  DB_PASSWORD="$(openssl rand -hex 24)"
  DB_ROOT_PASSWORD="$(openssl rand -hex 24)"
  # 64 byte hex = 128 ký tự — đủ entropy cho HMAC-SHA256 JWT
  JWT_SECRET="$(openssl rand -hex 64)"

  cat > "$ENV_FILE" <<EOF
# ──────────────────────────────────────────────────────────────
# Auto-generated by scripts/docker-init.sh on $(date '+%Y-%m-%d %H:%M:%S')
# KHÔNG commit file này vào git. KHÔNG share. Backup riêng nếu cần.
# ──────────────────────────────────────────────────────────────

# Database (MariaDB container)
DB_NAME=ketoan
DB_USER=ketoan_app
DB_PASSWORD=$DB_PASSWORD
DB_ROOT_PASSWORD=$DB_ROOT_PASSWORD

# JWT — sinh bằng openssl rand -hex 64
JWT_SECRET=$JWT_SECRET

# Bootstrap admin (TUỲ CHỌN — bỏ trống để dùng First-run Setup UI)
INITIAL_ADMIN_USERNAME=admin
INITIAL_ADMIN_PASSWORD=

# HTTP / CORS
APP_PORT=3001
ALLOWED_ORIGINS=
ENABLE_HSTS=0
EOF

  chmod 600 "$ENV_FILE" 2>/dev/null || true
  echo "✓ Đã sinh .env mới với secret ngẫu nhiên (chmod 600)"
  echo "  → DB_PASSWORD, DB_ROOT_PASSWORD, JWT_SECRET đều là openssl random"
  echo "  → INITIAL_ADMIN_PASSWORD để TRỐNG → frontend sẽ hiện trang Khởi tạo lần đầu"
fi

# ── 3. (Tuỳ chọn) chạy docker compose up ──────────────────────
if [ "$DO_UP" -eq 1 ]; then
  echo ""
  echo "▶ docker compose up -d --build"
  docker compose up -d --build

  echo ""
  echo "✓ Stack đã start. Kiểm tra:"
  echo "    docker compose ps"
  echo "    docker compose logs -f app"
  echo ""
  PORT="$(grep -E '^APP_PORT=' "$ENV_FILE" | cut -d= -f2)"
  PORT="${PORT:-3001}"
  echo "  Mở trình duyệt: http://localhost:$PORT"
  echo "  (lần đầu sẽ thấy trang 'Khởi tạo hệ thống lần đầu')"
fi
